import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const perfilStyles = StyleSheet.create({
    container: { 
        flex: 1, 
        backgroundColor: colors.backgroundAlt || '#F4F5F7'
    },
    scrollContent: { 
        paddingBottom: 60 
    },
    headerBanner: {
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        height: 140,
    },
    profileHeader: {
        alignItems: 'center',
        marginTop: -50,
        marginBottom: 30,
        paddingHorizontal: 20,
    },
    avatarContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: colors.backgroundAlt || '#F4F5F7',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 4,
        marginBottom: 12,
    },
    avatarText: {
        fontSize: 36,
        color: colors.primary,
        fontWeight: 'bold',
    },
    nome: {
        fontSize: 22,
        fontWeight: '700',
        color: colors.textMain,
        marginBottom: 6,
    },
    badge: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.05)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        alignItems: 'center',
    },
    badgeText: {
        color: colors.textMain,
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 6,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    section: {
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textMuted,
        marginBottom: 10,
        marginLeft: 4,
        letterSpacing: 1,
    },
    card: {
        backgroundColor: colors.white,
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border || '#E2E8F0',
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: colors.white,
    },
    menuIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: colors.backgroundAlt || '#F8FAFC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    menuText: {
        flex: 1,
        fontSize: 16,
        fontWeight: '500',
        color: colors.textMain,
    },
    divider: {
        height: 1,
        backgroundColor: colors.border || '#E2E8F0',
        marginLeft: 64,
    },
    actionContainer: {
        paddingHorizontal: 20,
        marginTop: 10,
        gap: 16,
    },
    botaoSair: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.white,
        paddingVertical: 16,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#FEE2E2', 
        gap: 8,
    },
    textoBotaoSair: {
        color: colors.danger,
        fontSize: 16,
        fontWeight: '700',
    },
    botaoDeletar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.danger,
        paddingVertical: 16,
        borderRadius: 16,
        gap: 8,
    },
    textoBotaoDeletar: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        justifyContent: 'center',
        padding: 24,
    },
    modalContent: {
        backgroundColor: colors.white,
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
    },
    modalIcon: {
        marginBottom: 16,
    },
    modalTitulo: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.textMain,
        marginBottom: 10,
    },
    modalTexto: {
        fontSize: 14,
        color: colors.textMuted,
        textAlign: 'center',
        marginBottom: 20,
        lineHeight: 22,
    },
    inputCodigo: {
        width: '100%',
        backgroundColor: colors.backgroundAlt || '#F8FAFC',
        borderWidth: 1,
        borderColor: colors.border || '#E2E8F0',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        textAlign: 'center',
        fontWeight: 'bold',
        color: colors.textMain,
        marginBottom: 16,
        letterSpacing: 3,
    },
    // NOVAS PROPRIEDADES ADICIONADAS PARA OS MODAIS DE E-MAIL E SENHA
    inputForm: {
        width: '100%',
        backgroundColor: colors.backgroundAlt || '#F8FAFC',
        borderWidth: 1,
        borderColor: colors.border || '#E2E8F0',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        color: colors.textMain,
        marginBottom: 16,
    },
    errorText: {
        color: colors.danger,
        fontSize: 13,
        marginBottom: 16,
        textAlign: 'center',
    },
    modalBotoes: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    botaoModal: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    botaoCancelar: {
        backgroundColor: colors.backgroundAlt || '#F8FAFC',
    },
    textoBotaoCancelar: {
        color: colors.textMain,
        fontSize: 15,
        fontWeight: '600',
    },
    botaoConfirmarPadrao: {
        backgroundColor: colors.primary,
    },
    textoBotaoConfirmarPadrao: {
        color: colors.white,
        fontSize: 15,
        fontWeight: '600',
    },
    botaoConfirmarExclusao: {
        backgroundColor: colors.danger,
    },
    textoBotaoConfirmarExclusao: {
        color: colors.white,
        fontSize: 15,
        fontWeight: '600',
    }
});